# Generated by Django 5.0.7 on 2024-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='name@web.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
