# Generated by Django 5.0.7 on 2024-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_email_alter_post_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alamat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
