# Generated by Django 5.1 on 2024-08-18 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_artikel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
