# Generated by Django 5.1 on 2024-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Blog', 'blog'), ('Berita', 'berita'), ('Jurnal', 'jurnal')], default='Blog', max_length=100),
        ),
    ]
