# Generated by Django 5.0.7 on 2024-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('kategori', models.CharField(max_length=255)),
                ('waktuPosting', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
