# Generated by Django 5.1 on 2024-08-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='sublished',
            new_name='published',
        ),
    ]
