# Generated by Django 5.1 on 2024-08-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': 'add', 'permissions': (('publish', 'can publish artikel'), ('edit', 'can edit artikel'))},
        ),
    ]
