# Generated by Django 5.1 on 2024-08-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_artikel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add',), 'permissions': (('can_publish', 'can publish artikel'), ('can_edit', 'can edit artikel'))},
        ),
    ]
