# Generated by Django 5.1 on 2024-08-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='content',
            field=models.CharField(default='programming', max_length=100),
            preserve_default=False,
        ),
    ]
